enum Letters {
    A = 'A',
    B = 'B',
    C = 'C',
    D = 'D',
    E = 'E',
    F = 'F',
    G = 'G',
    H = 'H',
    I = 'I',
    J = 'J',
    K = 'K',
    L = 'L',
    M = 'M',
    N = 'N',
    O = 'O',
    P = 'P',
    Q = 'Q',
    R = 'R',
    S = 'S',
    T = 'T',
    U = 'U',
    V = 'V',
    W = 'W',
    X = 'X',
    Y = 'Y',
    Z = 'Z'
};

// Let's say we wanted to extract out the dictionary key 
// so we could dynamically reference the dictionary elsewhere.
const dictionary = {
    [Letters.A]: 1,
    [Letters.B]: 2,
    [Letters.C]: 3,
    [Letters.D]: 4,
    [Letters.E]: 5,
    [Letters.F]: 6,
    [Letters.G]: 7,
    [Letters.H]: 8,
    [Letters.I]: 9,
    [Letters.J]: 10,
    [Letters.K]: 11,
    [Letters.L]: 12,
    [Letters.M]: 13,
    [Letters.N]: 14,
    [Letters.O]: 15,
    [Letters.P]: 16,
    [Letters.Q]: 17,
    [Letters.R]: 18,
    [Letters.S]: 19,
    [Letters.T]: 20,
    [Letters.U]: 21,
    [Letters.V]: 22,
    [Letters.W]: 23,
    [Letters.X]: 24,
    [Letters.Y]: 25,
    [Letters.Z]: 26
};